# Generated by Django 4.1.2 on 2022-11-01 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('team1', models.CharField(max_length=3)),
                ('school1', models.CharField(max_length=20)),
                ('position1', models.CharField(max_length=10)),
                ('versus', models.CharField(max_length=2)),
                ('team2', models.CharField(max_length=20)),
                ('school2', models.CharField(max_length=20)),
                ('position2', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
