# Generated by Django 4.1.2 on 2022-11-15 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgeId', models.CharField(max_length=20)),
                ('auth', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('judgeId', models.CharField(max_length=20)),
                ('tournamentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('note', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('team1', models.CharField(max_length=3)),
                ('school1', models.CharField(max_length=20)),
                ('members1', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=10)),
                ('team2', models.CharField(max_length=20)),
                ('school2', models.CharField(max_length=20)),
                ('members2', models.CharField(max_length=50)),
                ('position2', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=3)),
                ('results', models.CharField(max_length=20)),
                ('tournamentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('judgeId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('tournamentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rounds',
        ),
    ]
