# Generated by Django 4.1.2 on 2022-11-22 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0002_loginauth_note_round_tournament_delete_rounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round2',
            fields=[
                ('team1', models.CharField(max_length=20)),
                ('school1', models.CharField(max_length=20)),
                ('members1', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('school2', models.CharField(max_length=20)),
                ('members2', models.CharField(max_length=50)),
                ('position2', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=5)),
                ('results', models.CharField(max_length=20)),
                ('tournamentId', models.CharField(max_length=20)),
                ('judgeId', models.CharField(max_length=20)),
                ('roundId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),

    ]
