# Generated by Django 4.1.2 on 2022-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0005_round2_delete_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='judgeId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='round2',
            name='tournamentId',
            field=models.CharField(max_length=50),
        ),
    ]
