# Generated by Django 4.1.2 on 2022-11-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0006_delete_round_alter_round2_judgeid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
