# Generated by Django 4.1.2 on 2022-11-22 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0007_delete_note_delete_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('judgeId', models.CharField(max_length=50)),
                ('tournamentId', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=250)),
            ],
        ),
    ]
